
// Mocks generated by Mockito 5.0.17 from annotations
// in myapp/test/screens/add_farm_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as i4;

import 'package:mockito/mockito.dart' as i1;
import 'package:myapp/models/farm_model.dart' as i5;
import 'package:myapp/services/farm_service.dart' as i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class FakeFarm_0 extends i1.Fake implements i5.Farm {}

/// A class which mocks [FarmService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFarmService extends i1.Mock implements i3.FarmService {
  MockFarmService() {
    i1.throwOnMissingStub(this);
  }

  @override
  i4.Future<i5.Farm> createFarm(i5.CreateFarmRequest? request) =>
      (super.noSuchMethod(Invocation.method(#createFarm, [request]),
              returnValue: Future<i5.Farm>.value(FakeFarm_0()))
          as i4.Future<i5.Farm>);
}
